[package]
name = "nyaadle"
version = "2.0.0-alpha.2"
authors = ["Joash Christian Liwanag <nightlock0326@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rss = { version = "1.8.0", features = ["from_url"] }
reqwest = "0.9.24"
error-chain = "0.12.2"
config = "0.10.1"
dirs = "2.0.2"
rusqlite = "0.24.1"