[package]
name = "nyaadle"
version = "2.1.0"
authors = ["Joash Christian Liwanag <nightlock0326@gmail.com>"]
edition = "2018"
description = "A small rss parser and downloader for a certain cat-themed website"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rss = { version = "1.8.0", features = ["from_url"] }
reqwest = "0.9.24"
error-chain = "0.12.2"
dirs = "2.0.2"
rusqlite = { version = "0.24.1", features = ["bundled"] }
clap = { git = "https://github.com/clap-rs/clap/", features = [ "yaml" ] }
cursive_table_view = { git = "https://github.com/BonsaiDen/cursive_table_view.git"}

[dependencies.cursive]
version = "0.15"
default-features = false
features = [ "crossterm-backend" ]

[patch.crates-io.enumset_derive]
git = "https://github.com/ocboogie/enumset"
branch = "span-fix" 

